### ISSUE TITLE
request: Capture shutdown DockableWindow events

### ISSUE THREAD

**Issue by downloadproject** [pthom/imgui_bundle#112]
How to capture shutdown DockableWindow events. Thank you

**Comment by pthom** [comment]
Hi,

I'm not sure I understood your need. 
However if you need to know whether a window is opened or not, you can

1. Query its pointer:
C++
```cpp
        auto window = HelloImGui::GetRunnerParams()->dockingParams.dockableWindowOfName("My Window");
```

Python:
```python
window =     hello_imgui.get_runner_params().docking_params.dockable_window_of_name("My Window")
```

2.  Query whether it is visible: `window->isVisible`

```

**Comment by downloadproject** [comment]
Thank you!     
DockableWindow  have a close button.  Some windows I don't want to close., so I want to intercept this button closure event.

**Comment by pthom** [comment]
Well, at the moment there is no OnClose callback. The best you can do is check whether it was closed on the next frame.

For this you might use the callback `runnerParams.callbacks.PreNewFrame` (this callback is called before ImGui::NewFrame, so that the window is not yet hidden. You cannot display any Gui in this callback!)

Inside this callback, you can check your window open/close status. If you want to cancel the closing, you can do flip the `isVisible`flag. Also, you may also set a boolean flag that  later cause a DialogBox to be shown.

**Comment by downloadproject** [comment]
thank you！

**Comment by downloadproject** [comment]
How to add such a callback function？

**Comment by pthom** [comment]
> How to add such a callback function？

Your question is not clear enough
