### ISSUE TITLE
[Question] Non-OpenGL backend support (Metal)

### ISSUE THREAD

**Issue by curldivergence** [pthom/imgui_bundle#115]
Hi! Sorry if I'm missing something obvious, but do I understand correctly that like `hello-imgui` on which it is based, `imgui-bundle` supports only OpenGL as a backend? My use case is an app that uses Metal for rendering, and I'm curious if it's possible to use `imgui-bundle` for overlay UI, or I should stick with the "raw" `ImGui`? Thanks!

**Comment by pthom** [comment]
Hello,

For the moment, HelloImGui only supports Glfw and SDL with OpenGL3. 

However, you could choose to still use ImGui Bundle, in order to use the additional widgets it provides, but you will not be able to use HelloImGui with a Metal backend (so that you will have to use your own rendering loop).

**Comment by curldivergence** [comment]
Got it, thanks a lot for your help!
