### ISSUE TITLE
Python socket communication working on separate thread slows down when imgui bundle running in parel.

### ISSUE THREAD

**Issue by SebastianMilosz** [pthom/imgui_bundle#124]
We are using Hello Imgui from imgui bundle in our Python application. In a separate thread we have code that use sockets for receiving some data in the loop. We have notice that this thread significantly slows down when we have gui running in parel

**Comment by novichikhin** [comment]
same problem when sending an http request in separate thread

@pthom

**Comment by pthom** [comment]
Hi,

As you probably know, due to the GIL (Global Interpreter Lock), only one thread can execute Python code at the same time. Since ImGui is an immediate Gui mode library, it refreshes the screen from scratch at each frame. This is fast, however in python's multithreaded mode, this might slow down other threads.

As mentioned in [the threading page](https://docs.python.org/3/library/threading.html) for python, it would be advisable to use [multiprocessing](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing) instead.
When using multiprocessing, python provides a dedicated [message queue](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue), which is quite efficient and expressive.

Anyhow, you might want to reduce the FPS of the app when idling, see `hello_imgui.RunnerParams.fpg_idling`

```python
class FpsIdling:
    """*
     @@md#FpsIdling

    **FpsIdling** is a struct that contains Fps Idling parameters

    * `fpsIdle`: _float, default=9_.
      ImGui applications can consume a lot of CPU, since they update the screen very frequently.
      In order to reduce the CPU usage, the FPS is reduced when no user interaction is detected.
      This is ok most of the time but if you are displaying animated widgets (for example a live video),
      you may want to ask for a faster refresh: either increase fpsIdle, or set it to 0 for maximum refresh speed
      (you can change this value during the execution depending on your application refresh needs)
    * `enableIdling`: _bool, default=true_.
      Set this to False to disable idling (this can be changed dynamically during execution)
    * `isIdling`: bool (dynamically updated during execution)
      This bool will be updated during the application execution, and will be set to True when it is idling.
    * `rememberEnableIdling`: _bool, default=true_.
      If True, the last value of enableIdling is restored from the settings at startup.
    @@md

    """
    # float fpsIdle = 9.f;    /* original C++ signature */
    fps_idle: float = 9.
    # bool  enableIdling = true;    /* original C++ signature */
    enable_idling: bool = True
    # bool  isIdling = false;    /* original C++ signature */
    is_idling: bool = False
    # bool  rememberEnableIdling = true;    /* original C++ signature */
    remember_enable_idling: bool = True
```

**Comment by pthom** [comment]
Hi,

Speed should now be improved when running multithreaded code: see [related issue with the GIL](https://github.com/pthom/imgui_bundle/issues/171)
