### ISSUE TITLE
Initialize ImmVison from python

### ISSUE THREAD

**Issue by davidot** [pthom/imgui_bundle#134]
Really enjoying this nicely bundled version of Imgui accessible via python.
However I ran into some issues when extending the code at [bindings/imgui_bundle/demos_python/demos_immapp/imgui_example_glfw_opengl3.py](https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/demos_python/demos_immapp/imgui_example_glfw_opengl3.py)

I was trying to display some graphs made with matplotlib using `immvision.image_display` which works fine with an app setup with `immapp.run(...)`.
However in the demo code where you setup gl yourself there does not seem to be any way to access initializing immvision. 
Am I missing something or is this just not possible?
I could try adding some bindings to immvision but I'm not sure that is the correct solution here.

Also if there is some other/better way to display dynamic buffers, would love to know.

**Comment by pthom** [comment]
Hi, thanks for the nice feedback!

I fixed the issue inside ImmVision here: https://github.com/pthom/immvision/commit/d49fcc8b70c9dbdb76fcaa8b65cf70821ee009d8

You will need to build the bundle by yourself (`pip install -v -e .`) since I did not push a release as of now. 

Please tell me if it works on your side!

**Comment by davidot** [comment]
Wow very fast, thanks! Yeah it works now
