### ISSUE TITLE
Using the `@overload` decorator with overloaded functions

### ISSUE THREAD

**Issue by corbane** [pthom/imgui_bundle#139]
Hello,

At the beginning of the year, I had not noticed this problem, but today when opening an imgui_bundle project in VSCode (configured with Python by default: Pylance), I get errors with overloaded functions:

![image](https://github.com/pthom/imgui_bundle/assets/8430545/66c7f3b8-6fe7-4dca-bcbf-81247d5f4674)

Reading PEP 484 from python 3.5: https://peps.python.org/pep-0484/#function-method-overloading
I reformatted some `.pyi` files with the `@overload` decorator:

![image](https://github.com/pthom/imgui_bundle/assets/8430545/cbb5bdf5-840e-492f-a1a7-48561f5b627f)

The solution was given to me by [this link](https://stackoverflow.com/questions/71435368/how-does-the-type-callable-show-two-overloaded-signatures-in-pycharm) which concerns PyCharm and Typeshed.
It therefore seems that this error is not specific to Pylance but an error in respecting PEP 484.

Is it possible in future versions to add the `@overload` operators?
merci

**Comment by pthom** [comment]
Hello,

Since I had some time today, I worked on this. I needed to adapt the autogenerator. It went smoothly, so I updated the stubs in [this commit](https://github.com/pthom/imgui_bundle/commit/73297c6260e85e06bf182418b520c18a997e7598)

You will need to build from source: see https://pthom.github.io/imgui_bundle/#_build_and_install_instructions

**Comment by corbane** [comment]
Ha! Great!

Where is the autogenerator located in the repository?

**Comment by pthom** [comment]
Yes, the generator is indeed there. It is a big piece of software, which I did not take to document yet
