### ISSUE TITLE
ImGuiColorTextEdit: missing GetSelection()

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#169]
Posting here as can't post issues on your fork.

ImGuiColorTextEdit has SetSelection but not GetSelection.
Something like this should do the trick:
```c++
void TextEditor::GetSelection(Coordinates & aStart, Coordinates & aEnd) // or return a tuple
{
	aStart = mState.mSelectionStart;  // or perhaps SanitizeCoordinates(mState.mSelectionStart), thats done for cursor position
	aEnd = mState.mSelectionEnd;
}
Coordinates TextEditor::GetSelectionStart()
{
	return mState.mSelectionStart;  // or perhaps SanitizeCoordinates(mState.mSelectionStart), thats done for cursor position
}
Coordinates TextEditor::GetSelectionEnd()
{
	return mState.mSelectionEnd;  // or perhaps SanitizeCoordinates(mState.mSelectionEnd), thats done for cursor position
}
```
Could you consider adding that to your fork?

**Comment by pthom** [comment]
Hello

> Posting here as can't post issues on your fork.
You can now post issues there.

> ImGuiColorTextEdit has SetSelection but not GetSelection. Something like this should do the trick...

I did the modification. 

However this kind of changes is actually easy to do, so that you may consider trying them on your side and submit a PR.

Here is what I had to do:

1. Add GetSelectionStart / GetSelectionEnd

```cpp
TextEditor::Coordinates TextEditor::GetSelectionStart(int aCursor) const
{
    if (aCursor == -1)
        aCursor = mState.mCurrentCursor;
    return mState.mCursors[aCursor].mSelectionStart;
}

TextEditor::Coordinates TextEditor::GetSelectionEnd(int aCursor) const
{
    if (aCursor == -1)
        aCursor = mState.mCurrentCursor;
    return mState.mCursors[aCursor].mSelectionEnd;
}
```

2. Run `imgui_bundle/external/ImGuiColorTextEdit/bindings/generate_imgui_color_text_edit.py`

(this requires to install litgen, but I wrote a nice [documentation](https://pthom.github.io/litgen) for it, along with [install instructions](https://pthom.github.io/litgen/litgen_book/01_05_10_install.html) 

3. Compile & push


I did not test the functionality. Can you please confirm that it works?

**Comment by dcnieho** [comment]
Thanks! I did not know the library has some kind of multi cursor support.
The reason i didn't send a pull request this time is because i'm not set up to test it, nor did i know what would be the best interface that you could easily generate bindings for (I guess my return through references wasn't ideal).
I'll test when its released!
Thanks again.

**Comment by pthom** [comment]
> return through references wasn't ideal

No, because from the caller side, semantically it means "transfer an input value and receive it after modification", not "receive an output value"

Returning a tuple would have worked.

> I'll test when its released!

Each time a push is made on the main branch, the [wheels workflow](https://github.com/pthom/imgui_bundle/actions/workflows/wheels.yml) produces artifacts that contain wheels for all platforms. Could you test those?

**Comment by dcnieho** [comment]
Your commit works!
It did reveal some debug output (that was already in the code and should be removed) and some bug in the selection logic of the editor).

1. debug output. lines 2081 and 2102 print stuff to the console (when extending a selection leftward with the arrow keys while holding down shift). Those lines should probably be deleted.
2. bug. Put your cursor somewhere in the text. Make a selection by holding down shift, e.g. going 5 characters from right to left. Now press left once without shift held, cursor doesn't move, selection is removed (correct, same behavior of the editor in my browser here). Now hold down shift and go in the other direction with the arrow keys, left to right. See that the selection is edited from the original selection location, not restarted from the new location. If instead after you cancel the selection you make any navigation action (like going left one more time), then things do work correctly. So some stale selection seems to be left around when its cancelled. I can't quite understand the code, but i think it is the logic on lines 2086-2089 (and 2158-2161) that seems to explicitly do this, possibly. Of course nothing for you to fix, but wanted to log it somewhere (upstream isn't really maintained, right?)

**Comment by pthom** [comment]
> Bug. Put your cursor somewhere in the text. Make a selection by holding down shift

I've had so many hard issues to work on these days, that this one was kind of a toy. I corrected it.

**Comment by dcnieho** [comment]
That simple? Cool! Nice work.
Man let me say again that imgui_bundle is making my work a lot better (and more fun!), so glad i found it and very happy with the quality you deliver and your responsiveness.
