### ISSUE TITLE
windows render as all white on Windows 10 enterprise VMWare virtual machine 

### ISSUE THREAD

**Issue by kuchi** [pthom/imgui_bundle#172]
I am trying to run imgui_bundle on a virtual Windows 10 enterprise machine that I connect to via VMWare Horizon Client. These are virtual windows systems in our data center.

The imgui_bundle windows just render as white (see right window in below image). I also have an app using `dearpygui` (another python imgui wrapper) and that displays as expected (left window). 

<img width="1289" alt="image" src="https://github.com/pthom/imgui_bundle/assets/1454335/d538ef97-4f10-48dc-be56-b424f897b37b">

I'm not certain what would cause that. Looking around, I did find some comments that this can happen when when the [gl buffers are not swapped](https://stackoverflow.com/questions/74599604/why-is-there-a-blank-white-screen-rendering). Although I can't image that would be it since it works on my real physical windows 11 systems. Maybe it is some difference with the VMWare graphics drivers. Is there a setting I need to change?

System Info:

Windows 10 Enterprise
Intel(R) Xeon(R) Gold 6254 CPU @ 3.10GHz   3.09 GHz
64-bit operating system, x64-based processor
display: VMware SVGA 3D

If there is other helpful diagnostic info I can provide let me know.

Thanks.

**Comment by pthom** [comment]
Hello Anthony,

Good to hear from you! 

I never used VmWare Horizon Client, so that it is difficult for me to help you. 

I suspect DearPyGui also uses OpenGL, but perhaps a different version (bundle uses OpenGL3), or with different rendering techniques. Are there logs given by imgui_bundle that might indicate an error?

Below are some rough advices. I will be honest, as I don't know this tool, those are an extract from a conversation I had with ChatGPT on the subject:

* Try Different Protocols: Switch between PCoIP and Blast Extreme to see if the issue persists across both protocols.

* Check Server Configuration: Ensure the server is configured correctly for GPU use and that it has the necessary resources.

* Consult Logs and Documentation: Check VMware Horizon logs and documentation for any known issues or specific settings required for OpenGL applications.

* Check VMware Tools: Ensure VMware Tools is installed and up-to-date on the virtual machine. This tool enhances the performance of virtual machines and includes drivers for better graphics support.

* VM Configuration: Review the VM's configuration, specifically the allocated graphics resources. Increasing video memory or enabling additional 3D capabilities might help.

**Comment by pthom** [comment]
If this is not enough, ping me by email, I'll try to help by remote connection. You will need a working installation of Visual Studio on the Windows 10 enterprise machine, so that we can debug.

I'm available today

**Comment by kuchi** [comment]
Pascal,

From talking with the system admins those systems have some GPU limitations so I believe it is a hardware limitation. So you can close this issue. 

Thanks for your help with this.
