### ISSUE TITLE
Possibility to add imgui notification library ImGuiNotify

### ISSUE THREAD

**Issue by kuchi** [pthom/imgui_bundle#187]
I was wondering if you might have interest to add [ImGuiNotify](https://github.com/TyomaVader/ImGuiNotify/tree/Dev) to `imgui_bundle`. I would be happy to sponsor the addition financially if you think this would be an appropriate library to add to `imgui_bundle` and you don't see long term issues including this. 

And as always, thanks so much for developing `imgui_bundle`. It is a wonderful.

**Comment by pthom** [comment]
Hello Anthony,

Long time no talk. It's nice to hear from you!

I had a look at the library you mentioned: it only works under Windows and Linux, but not Mac OS, which is an issue for me, because I want the bundle to work on all platforms. Also, the code quality would need to be improved, before I can integrate it. This would require that I post quite a few pull requests to this library before being able to integrate it. 

However, there might be a much easier solution. ImGui bundle already integrates a library named `Portable File Dialogs`, which provides notifications and message boxes which are native to the system (i.e. the notifications would be provided by Windows in your case, and they would show in the notification center).

Here is a sample usage:

```python
from imgui_bundle import imgui, hello_imgui, portable_file_dialogs as pfd


msg: pfd.message | None = None
notif: pfd.notify | None = None


def gui() -> None:
    global msg, notif
    if imgui.button("Add Notif"):
        pfd.notify("Hello", "World", pfd.icon.error)
    if imgui.button("Add message"):
        msg = pfd.message("Hello", "World", pfd.choice.yes_no_cancel, pfd.icon.warning)
    if msg is not None and msg.ready():
        print("msg ready: " + str(msg.result()))
        msg = None



def main() -> None:
    hello_imgui.run(gui)


if __name__ == "__main__":
    main()
```

Is that enough? Or are there other features from ImGuiNotify that you want to use, in which case I would be happy to discuss this with you. 

---

Also, I'm working on a brand new project which I would really like to discuss with you because I think you might be interested and your inputs would be valuable to me. Would you have a moment for us to have a telephone conversation or maybe a video call so that I can show you this new project?  I'm working from home this week, so I'm quite available at a France working times. Let's exchange by email about that.

**Comment by kuchi** [comment]
Pascal,Note - I took my wife’s last name so my name is now Anthony Rynes. I didn’t realize that the portable file dialogs has the notifications. That is better and I also use Mac OS. I didn’t notice that library isn’t fully cross platform. I agree it doesn’t actually make sense. Thanks for looking into it. Yes, I would be glad to talk to you. If we do a teams call I could also show you what I have been using imgui bundle to create. One of the main applications i have been writing is for video measurements. Just let me know what time works for you. I get up quite early most days (I’m up now). Send me an email at my work address if you have at time that works ***@***.*** I hope at some point I can release it as open source or at least some of the smaller apps. However it is quite a process at my work to open source projects. I know it would be nice to have more sample apps to showcase what you can do with imgui bundle. I would really like to help get more people aware of your project. If there are ways I can further support your work I would be happy to try. Now that you are registered in our system it would be much easier. Anthony RynesOn Mar 12, 2024, at 3:20 AM, Pascal Thomet ***@***.***> wrote:﻿
Hello Anthony,
Long time no talk. It's nice to hear from you!
I had a look at the library you mentioned: it only works under Windows and Linux, but not Mac OS, which is an issue for me, because I want the bundle to work on all platforms. Also, the code quality would need to be improved, before I can integrate it. This would require that I post quite a few pull requests to this library before being able to integrate it.
However, there might be a much easier solution. ImGui bundle already integrates a library named Portable File Dialogs, which provides notifications and message boxes which are native to the system (i.e. the notifications would be provided by Windows in your case, and they would show in the notification center).
Here is a sample usage:
from imgui_bundle import imgui, hello_imgui, portable_file_dialogs as pfd


msg: pfd.message | None = None
notif: pfd.notify | None = None


def gui() -> None:
    global msg, notif
    if imgui.button("Add Notif"):
        pfd.notify("Hello", "World", pfd.icon.error)
    if imgui.button("Add message"):
        msg = pfd.message("Hello", "World", pfd.choice.yes_no_cancel, pfd.icon.warning)
    if msg is not None and msg.ready():
        print("msg ready: " + str(msg.result()))
        msg = None



def main() -> None:
    hello_imgui.run(gui)


if __name__ == "__main__":
    main()
Is that enough? Or are there other features from ImGuiNotify that you want to use, in which case I would be happy to discuss this with you.

Also, I'm working on a brand new project which I would really like to discuss with you because I think you might be interested and your inputs would be valuable to me. Would you have a moment for us to have a telephone conversation or maybe a video call so that I can show you this new project?  I'm working from home this week, so I'm quite available at a France working times. Let's exchange by email about that.

**Comment by kuchi** [comment]
The suggestions you made work and the library I suggested is not cross platform.
