### ISSUE TITLE
ModFlags_ enum is missing

### ISSUE THREAD

**Issue by oxysoft** [pthom/imgui_bundle#256]
Hello, attempting to make some keychords for my shortcuts and I can't find the enum for `ctrl`, `alt` and `shift` modifiers!

**Comment by oxysoft** [comment]
Hm seems that's it's in the Key enum as `im_gui_mod_ctrl`, etc. not sure if that's a quirk of the bindings or if imgui has been changed, but the name containing `im_gui_mod` as a prefix indicates to me that this may indeed be a strange quirk of the bindings

**Comment by pthom** [comment]
The bindings are auto-generated from the C++ code, so the official source is imgui.h in the official repo.

See https://github.com/ocornut/imgui/blob/29cff2be06860cadbc7557cc64f29159468213e2/imgui.h#L1527-L1532 : there is no ModFlags_ enum (and if it existed in the past, it was removed by Omar) 
```
enum ImGuiKey : int {
    // Keyboard
    ImGuiKey_None = 0,
    ImGuiKey_Tab = 512,             // == ImGuiKey_NamedKey_BEGIN
    ImGuiKey_LeftArrow,
    ImGuiKey_RightArrow,
    ...
    ImGuiMod_None                   = 0,
    ImGuiMod_Ctrl                   = 1 << 12, // Ctrl (non-macOS), Cmd (macOS)
    ImGuiMod_Shift                  = 1 << 13, // Shift
    ImGuiMod_Alt                    = 1 << 14, // Option/Menu
    ImGuiMod_Super                  = 1 << 15, // Windows/Super (non-macOS), Ctrl (macOS)
    ImGuiMod_Mask_                  = 0xF000,  // 4-bits
   ...
};
```

There is a quirk which is that `ImGuiMod_Ctrl` was translated to `im_gui_mod_ctrl` (an issue in the snake_case conversion).

I'm not sure I shall change it because some users might be relying on it already. 

Leaving this issue opened until I come to a decision.

**Comment by dcnieho** [comment]
Yes, i am using `im_gui_mod_ctrl` already, but would be happy to change to `imgui.Key_.mod_ctrl`, which i guess would be the logical name for it.

**Comment by pthom** [comment]
@dcnieho : this was fixed inside https://github.com/pthom/imgui_bundle/commit/be5ab1328d1a66a1f1660f4a01803e11c8351353

However, this change has quite a few impact in the internal API. For the best, I think

**Comment by pthom** [comment]
@dcnieho 

See https://github.com/pthom/imgui_bundle/commit/f8db311b9c0828330e6b277238243ae3ccb8db76

Which was obtained with [this change](https://github.com/pthom/litgen/commit/5d4eea705eb7eb17229ac73070a8fcb20b2dcfc4) in litgen.

I implemented this with a concrete fix, specific to ImGui, and I avoided using regexes and the ["two problems"](https://regex.info/blog/2006-09-15/247) plague :-)

**Comment by dcnieho** [comment]
That cleans it up super nicely! Thanks!n Probably better to just have this special case indeed :)
