### ISSUE TITLE
ImFontAtlas::GetTexDataAsRGBA32()

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#31]
I asked about getting access to `ImFontAtlas::GetTexDataAsRGBA32()`. You implemented `font_atlas_get_tex_data_as_rgba32`, but i notice that it is only present (commented out) in the .pyi file. Have you nixed it and i missed the testing window?

**Comment by dcnieho** [comment]
By the way, instead of a free function, could it be made part of the wrapper font atlas? I guess this needs some support in the generator.

I guess what happens now is that due to function signature `ImFontAtlas::GetTexDataAsRGBA32()` is discarded, can't be automatically wrapped. What you might be able to do, at some high level, is:
1. provide the manual implementation at the C++ side like you already have
2. when configuring your generator, have a list of function translations, where you say `src="ImFontAtlas::GetTexDataAsRGBA32()"` should be mapped to ´<your free function here>´. `pybind`'s def supports that after all, if needed wrapped in a lambda.

That would give you the flexibility needed to provide functions manually where needed, but still provide the nice interface with member functions to the end user. This would also apply to [`imgui.set_io_ini_filename()`](https://github.com/pthom/imgui_bundle/issues/17) hopefully, since `pybind`'s `def_property` can be passed getter and setter function pointers or lambdas.

**Comment by pthom** [comment]
> Have you nixed it and i missed the testing window?

It was broken.
I pushed a commit where it works: 8b60a252
Proof (from sandbox_app.py in this commit, which I will *not* maintain)
<img width="539" alt="image" src="https://user-images.githubusercontent.com/7694091/205953954-ef539a33-72a4-4c7a-98d6-233537ef3aea.png">

However, do you need this function, and do you plan to use it; or did you ask because you have issues with font loading?

----

> By the way, instead of a free function, could it be made part of the wrapper font atlas? I guess this needs some support in the generator, etc etc.

This is a different subject. I cannot handle all the battles together.

**Comment by pthom** [comment]
I'm closing this issue as completed, since font_atlas_get_tex_data_as_rgba32 does work.

--- 
Concerning your suggestion of mapping outside lambda, it could be interesting but would require a lot of work in the generator which is already a very very complex beast.

May be we could reopen a different issue concerning this. However, I wondering whether I need to think of an alternative way to store suggestions for possible later development (outside of GH issues list). I'm not sure GH issues is the right tool, I still need to familiarize with it.

**Comment by dcnieho** [comment]
Nice thanks, it works for me too. I use it to check that font texture generation worked. If the returned texture is empty (no pixels), then it errored and i should reduce font scale. At least thats what i think the logic is of the code i inherited.
