### ISSUE TITLE
Will ImPlotPlot struct fields be added to the python bindings in the future?

### ISSUE THREAD

**Issue by cdobrescu** [pthom/imgui_bundle#87]
Hi, 
first of all thanks for such a great work on porting (and packaging) Imgui _and co._ to python. I was playing with Implot in python and wanted to access the current plot data between BeginPlot and EndPlot. That's when I've noticed that there are no python bindings to access the fields of the Plot structure but only bindings for the struct methods
```cpp
struct ImPlotPlot
{
    ImGuiID              ID;
    ImPlotFlags          Flags;
    ImPlotFlags          PreviousFlags;
    ImPlotLocation       MouseTextLocation;
    ImPlotMouseTextFlags MouseTextFlags;
    ImPlotAxis           Axes[ImAxis_COUNT];
    ImGuiTextBuffer      TextBuffer;
    ImPlotItemGroup      Items;
    ImAxis               CurrentX;
    ImAxis               CurrentY;
    ImRect               FrameRect;
    ImRect               CanvasRect;
    ImRect               PlotRect;
    ImRect               AxesRect;
    ImRect               SelectRect;
    ImVec2               SelectStart;
    int                  TitleOffset;
    bool                 JustCreated;
    bool                 Initialized;
    bool                 SetupLocked;
    bool                 FitThisFrame;
    bool                 Hovered;
    bool                 Held;
    bool                 Selecting;
    bool                 Selected;
    bool                 ContextLocked;
```

Are you planning on adding bindings for the fields in the future? Is there something that's preventing this from happening? Should I give it a try myself and submit a PR?

The motivation would be that I want to implement a different plot UpdateInput behaviour for my plot and for that I need to access the plot inner components

**Comment by pthom** [comment]
Hi,

Thanks for mentioning this! This was due to a simple mistake in the [generator config](https://github.com/pthom/imgui_bundle/commit/7761907e215d1cf6aa1e208262e9c42ca44fc9bd#diff-955ff76150ab41c6da442f3c03e87ab1d4f61773884670275e2833e0b356372b)

I fixed this in [this commit](https://github.com/pthom/imgui_bundle/commit/7761907e215d1cf6aa1e208262e9c42ca44fc9bd)


You will need to [compile from source](https://pthom.github.io/imgui_bundle/#_install_for_python) until I publish a new release.

Please tell me if it works for you.

Cheers

**Comment by cdobrescu** [comment]
Wow! Thank you for your quick update! Yes everything I needed (and more) is in place!
