### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#94]
I have been looking into how you do your docs. I wasn't familiar with asciidoc, but it looks like a great tool. I see you have a shellscript (https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/doc/scripts/build_doc.sh) for generating the docs. I am wondering how its used. Do you manually deploy to https://pthom.github.io/imgui_bundle/, or is that part of the CI? This could be a godsend for a project unrelated to imgui_bundle that i am doing.

**Comment by pthom** [comment]
Hi,

> I see you have a shellscript (https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/doc/scripts/build_doc.sh) for generating the docs. I am wondering how its used. Do you manually deploy to https://pthom.github.io/imgui_bundle/, or is that part of the CI?

To answer your question directly, it is called by cmake if the project is configured with `-DIMGUI_BUNDLE_BUILD_DOC=ON` (see bindings/imgui_bundle/doc/CMakeLists.txt).

Then, I configured Github pages like this: 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/7694091/224745588-fa3bffe7-7afb-4e29-ae91-d22e1f9a9222.png">

So that whenever I push something on the `doc` branch, the content of the `docs/` folder is deployed to  https://pthom.github.io/imgui_bundle/.

This folder content is generated from the asciidocs sources in bindings/imgui_bundle/doc and bindings/imgui_bundle/doc/doc_parts, via this script. This script also generates bindings/imgui_bundle/doc/imgui_bundle_demo_parts which is used in the demo (those are markdown exports).
 
I discovered asciidocs a few months ago and it is indeed quite powerful (you can aggregate document parts, extract parts from the actual code, export to mardown, html, etc.)

**Comment by pthom** [comment]
Closing this, as this was primarily a question
