### ISSUE TITLE
Python usage with SDL 

### ISSUE THREAD

**Issue by bolducke** [pthom/imgui_bundle#99]
Hi! 

I am currently using pyimgui with pySDL and moderngl. pyimgui is doing what I want but is a little bit limited. I would like to switch to imgui_bundle for its completness. 

Is there an other way to initialize imgui than through immap? All example initialise the window through it.

Update: I saw an example on GLFW, IMGUI and OpenGL. Is there a backend for SDL2? 

Thx for your time. :)

**Comment by pthom** [comment]
Hi!

Ther are actually two example of using imgui without ImmApp. 

If you open the [online interactive manual](https://traineq.org/ImGuiBundle/emscripten/bin/demo_imgui_bundle.html) and go to Immediate Apps, you will see two demos for this:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/7694091/226070493-068e502c-dccf-42cc-ab84-664cd992284b.png">

They are using glfw, and some users were very successful with them.

At the moment, there is no way to do it with SDL, since this would require to find a way to let Dear ImGui Bundle use the same dll as pySDL: I found a (rather complex) way to do it for glfw, but I did not explore that for SDL yet. Would it be possible for your project to switch to glfw?

**Comment by pthom** [comment]
Update: using pySDL is now also supported. 

See example: https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/demos_python/demos_immapp/imgui_example_sdl2_opengl3.py 

Note: this version is not yet available via Pypy, you will have to [install the package from source](https://pthom.github.io/imgui_bundle/#_install_for_python)

**Comment by bolducke** [comment]
I appreciate your comment. This is exactly what I was looking for. I'm using SDL and in a few corner case, GLFW lack support.

I downloaded the lastest source and tested your examples. It seems that I'm having a segmentation fault after a black window is popping out. I will try to pinpoint the source of error in the coming days.

**Comment by pthom** [comment]
on my side, the sdl example works under macOs and windows (after a simple fix: https://github.com/pthom/imgui_bundle/commit/f69669c513d82d4fc49114e69366f65233f9e75d).
